# Generated by Django 4.1.5 on 2023-10-10 08:30

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_trainingjob_ended_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedata",
            name="file",
            field=models.FileField(
                upload_to="static", validators=[home.models.validate_file_extension]
            ),
        ),
    ]
