# Generated by Django 4.1.5 on 2023-10-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_activatedata_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedata",
            name="file",
            field=models.FileField(upload_to="static"),
        ),
    ]
